import type { DiamondOffer, PaymentMethod, SupportContact, LevelUpPackage, Membership, PremiumApp } from './types';

export const APP_LOGO_URL = 'https://i.ibb.co/k2nGxqwY/1763225878291.jpg';
export const DEFAULT_AVATAR_URL = 'https://i.ibb.co/k2nGxqwY/1763225878291.jpg';

export const DIAMOND_OFFERS: DiamondOffer[] = [
  { id: 0, diamonds: 50, price: 45 },
  { id: 1, diamonds: 100, price: 85 },
  { id: 2, diamonds: 310, price: 250 },
  { id: 3, diamonds: 520, price: 420 },
  { id: 4, diamonds: 1060, price: 830 },
  { id: 5, diamonds: 2180, price: 1650 },
  { id: 6, diamonds: 5600, price: 4100 },
];

export const LEVEL_UP_PACKAGES: LevelUpPackage[] = [
  { id: 100, name: 'Level 6 Package', price: 90 },
  { id: 101, name: 'Level 10 Package', price: 150 },
  { id: 102, name: 'Level 15 Package', price: 210 },
  { id: 103, name: 'Level 20 Package', price: 280 },
  { id: 104, name: 'Level 25 Package', price: 350 },
  { id: 105, name: 'Level 30 Package', price: 420 },
];

export const MEMBERSHIPS: Membership[] = [
  { id: 200, name: 'Weekly Membership', price: 175 },
  { id: 201, name: 'Monthly Membership', price: 690 },
];

export const PREMIUM_APPS: PremiumApp[] = [
  { id: 300, name: 'YouTube Pro', price: 120, description: 'Ad-free & Background Play' },
  { id: 301, name: 'ChatGPT Pro', price: 450, description: 'Advanced AI Access' },
  { id: 302, name: 'CapCut Pro', price: 250, description: 'Premium Video Editing' },
  { id: 303, name: 'Spotify Premium', price: 100, description: 'Ad-free Music' },
  { id: 304, name: 'Netflix (1 Screen)', price: 180, description: '4K Ultra HD' },
];


export const BANNER_IMAGES: string[] = [
  'https://i.ibb.co/ZJ4z147/image.png',
  'https://i.ibb.co/kH77V5X/image.png',
  'https://i.ibb.co/b3S0S16/image.png',
  'https://i.ibb.co/VMyXgG3/image.png'
];

export const MIN_DEPOSIT_AMOUNT = 20;

export const PAYMENT_METHODS: PaymentMethod[] = [
    { name: 'bKash', logo: 'https://i.ibb.co/0jYf5XHR/Bkash-logo-PNG-1.png', accountNumber: '01XXXXXXXXX' },
    { name: 'Nagad', logo: 'https://i.ibb.co/h1TCCrpn/id-Npcxg37-S-1763218116295.png', accountNumber: '01XXXXXXXXX' },
    { name: 'Rocket', logo: 'https://i.ibb.co/x8gpgF7J/Rocket-mobile-banking-logo-svg.png', accountNumber: '01XXXXXXXXX' },
];

export const SUPPORT_CONTACTS: SupportContact[] = [
    { type: 'video', labelKey: 'howToBuyDiamond', link: 'https://youtu.be/c85fchKorAU?si=MzFb63eHFsb7VOiu' },
    { type: 'phone', labelKey: 'contactCallUs', link: 'tel:+8801234567890' },
    { type: 'whatsapp', labelKey: 'contactWhatsApp', link: 'https://wa.me/8801234567890' },
    { type: 'telegram', labelKey: 'contactTelegram', link: 'https://t.me/yourchannel' },
    { type: 'email', labelKey: 'contactEmailUs', link: 'mailto:support@ffshop.com' },
];

export const REWARD_ADS_ENABLED = true;
export const DAILY_AD_LIMIT = 20;
export const REWARD_PER_AD = 5; // in currency

// NEW APP SETTINGS DEFAULT WITH HYBRID ADS
export const DEFAULT_APP_SETTINGS = {
    appName: "FF SHOP",
    maintenanceMode: false,
    visibility: {
        diamonds: true,
        levelUp: true,
        membership: true,
        premium: true,
        earn: true
    },
    earnSettings: {
        dailyLimit: DAILY_AD_LIMIT,
        rewardPerAd: REWARD_PER_AD,
        adCooldownSeconds: 10,
        resetHours: 24,
        webAds: {
            active: true,
            url: '',
            duration: 15
        },
        adMob: {
            active: false,
            appId: 'ca-app-pub-3940256099942544~3347511713', // Test App ID
            rewardId: 'ca-app-pub-3940256099942544/5224354917', // Test ID
            bannerId: '',
            interstitialId: ''
        }
    }
};

export const TEXTS: any = {
  en: {
    appName: "FF SHOP",
    loginTitle: "Login to your Account",
    registerTitle: "Create an Account",
    email: "Email",
    name: "Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    login: "Login",
    register: "Register",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    welcome: "Welcome",
    balance: "Balance",
    currency: "৳",
    diamondOffers: "Diamond",
    buyNow: "Buy Now",
    bonus: "Bonus",
    purchase: "Purchase",
    confirmPurchase: "Confirm Purchase",
    cancel: "Cancel",
    enterUID: "Enter your Player UID",
    uidRequired: "Player UID is required.",
    uidNumeric: "Player UID must only contain numbers.",
    uidLength: "Player UID must be between 8 and 12 digits.",
    enterEmail: "Enter your Email",
    emailRequired: "Email is required.",
    emailInvalid: "Please enter a valid email address.",
    processingOrder: "Processing your order...",
    orderSuccessful: "Purchase Complete!",
    orderPending: "Your {diamonds} Diamonds will be added to your Free Fire account within 24 hours.",
    orderPendingGeneric: "Your '{packageName}' purchase is successful and will be added to your account shortly.",
    navHome: "Home",
    navWallet: "Wallet",
    navProfile: "Profile",
    navEarn: "Earn",
    addFunds: "Add Money",
    selectPayment: "Select Payment Method",
    amount: "Amount",
    profileSettings: "LANGUAGE",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    logout: "Logout",
    customerCare: "Customer Care",
    watchAds: "Watch Ads & Earn",
    watchAnAd: "Watch an Ad",
    adsWatched: "Ads Watched Today",
    youEarned: "You have earned",
    adLimitReached: "You have reached the daily ad limit.",
    watchAdsScreenTitle: "Watch Ads & Earn",
    watchAdsScreenDescription: "Watch short video ads to earn rewards and top up your balance.",
    rewardPerAd: "Reward Per Ad",
    dailyAdLimit: "Daily Ad Limit",
    totalEarned: "Total Earned",
    totalAdsWatched: "Total Ads Watched",
    ads: "Ads",
    uid: "Player UID",
    searchDiamonds: "Search diamonds (e.g., 100)",
    noOffersFound: "No offers found.",
    purchaseHistory: "Purchase History",
    statusCompleted: "Completed",
    statusPending: "Pending",
    statusFailed: "Failed",
    hi: "Hi",
    availableBalance: "Available Balance",
    supportPin: "Support Pin",
    weeklySpent: "Weekly Spent",
    totalSpent: "Total Spent",
    totalDeposit: "Total Deposit",
    totalOrder: "Total Order",
    logoutConfirmTitle: "Confirm Logout",
    logoutConfirmMessage: "Are you sure you want to log out?",
    logoutConfirmButton: "Confirm",
    viewDetails: "View Details",
    contactSupport: "Contact Support",
    myOrders: "My Orders",
    myCodes: "My Codes",
    myTransaction: "My Transaction",
    contactUs: "Contact Us",
    getInTouch: "Get in Touch",
    support: "Support",
    fundsAddedSuccessfully: "Funds added successfully!",
    addFundsError: "Please enter an amount and select a payment method.",
    changePassword: "Change Password",
    changePasswordTitle: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updatePassword: "Update Password",
    passwordChangedSuccess: "Password changed successfully!",
    passwordsDoNotMatch: "Passwords do not match.",
    incorrectCurrentPassword: "Current password is incorrect.",
    delete: "Delete",
    deleteConfirmTitle: "Confirm Deletion",
    deleteConfirmMessage: "Are you sure you want to delete this order? This action cannot be undone.",
    deleteConfirmButton: "Delete",
    ordersEmpty: "Your purchase history is empty.",
    rewardAdded: "Added to your balance!",
    minDepositError: `Minimum deposit amount is ৳${MIN_DEPOSIT_AMOUNT}.`,
    nextStep: "Next",
    previousStep: "Back",
    paymentInstructionsTitle: "Payment Instructions",
    paymentInstructionsBody: "Please send exactly {currency}{amount} to the following {methodName} number. Then enter the transaction ID in the next step.",
    accountNumberLabel: "Number",
    copy: "Copy",
    copied: "Copied!",
    paymentSentConfirmation: "I have sent the money",
    transactionIdLabel: "Transaction ID",
    transactionIdPlaceholder: "Enter the TrxID here",
    submitTransaction: "Submit",
    paymentPendingTitle: "Request Submitted",
    paymentPendingMessage: "Your money will be added to your account within 10 minutes, if the payment is successful.",
    addMoreMoney: "Add More Money",
    transactionIdRequired: "Transaction ID is required.",
    nextAdIn: "Next ad in",
    insufficientBalance: "Insufficient balance.",
    newBalance: "New Balance",
    editProfileTitle: "Edit Profile",
    saveChanges: "Save Changes",
    changePhoto: "Change Photo",
    saving: "Saving...",
    changesSaved: "Changes Saved!",
    uidOptional: "UID (Optional)",
    howToBuyDiamond: "How to Buy Diamond (Tutorial Video)",
    contactCallUs: "Call Us",
    contactWhatsApp: "WhatsApp",
    contactTelegram: "Telegram",
    contactEmailUs: "Email Us",
    rewardDepositMessage: "+{amount} to Wallet!",
    levelUpPackages: "Level Up",
    memberships: "Membership",
    premiumApps: "Premium App",
    notifications: "Notifications",
    noNotifications: "No notifications yet.",
    markAllRead: "Mark all as read",
    'Level 6 Package': 'Level 6 Package',
    'Level 10 Package': 'Level 10 Package',
    'Level 15 Package': 'Level 15 Package',
    'Level 20 Package': 'Level 20 Package',
    'Level 25 Package': 'Level 25 Package',
    'Level 30 Package': 'Level 30 Package',
    'Weekly Membership': 'Weekly Membership',
    'Monthly Membership': 'Monthly Membership',
  },
  bn: {
    appName: "এফএফ শপ",
    loginTitle: "আপনার অ্যাকাউন্টে লগইন করুন",
    registerTitle: "একটি অ্যাকাউন্ট তৈরি করুন",
    email: "ইমেল",
    name: "নাম",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    login: "লগইন",
    register: "নিবন্ধন করুন",
    noAccount: "কোনো অ্যাকাউন্ট নেই?",
    haveAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    welcome: "স্বাগতম",
    balance: "ব্যালেন্স",
    currency: "৳",
    diamondOffers: "ডায়মন্ড",
    buyNow: "এখনই কিনুন",
    bonus: "বোনাস",
    purchase: "ক্রয় করুন",
    confirmPurchase: "ক্রয় নিশ্চিত করুন",
    cancel: "বাতিল",
    enterUID: "আপনার প্লেয়ার ইউআইডি দিন",
    uidRequired: "প্লেয়ার ইউআইডি প্রয়োজন।",
    uidNumeric: "প্লেয়ার ইউআইডি শুধুমাত্র সংখ্যা হতে হবে।",
    uidLength: "প্লেয়ার ইউআইডি অবশ্যই 8 থেকে 12 সংখ্যার মধ্যে হতে হবে।",
    enterEmail: "আপনার ইমেইল দিন",
    emailRequired: "ইমেইল আবশ্যক।",
    emailInvalid: "অনুগ্রহ করে সঠিক ইমেইল দিন।",
    processingOrder: "আপনার অর্ডার প্রক্রিয়া করা হচ্ছে...",
    orderSuccessful: "ক্রয় সম্পন্ন!",
    orderPending: "আপনার {diamonds} ডায়মন্ড ২৪ ঘণ্টার মধ্যে আপনার ফ্রি ফায়ার অ্যাকাউন্টে যোগ করা হবে।",
    orderPendingGeneric: "আপনার '{packageName}' ক্রয় সফল হয়েছে এবং শীঘ্রই আপনার অ্যাকাউন্টে যোগ করা হবে।",
    navHome: "হোম",
    navWallet: "ওয়ালেট",
    navProfile: "প্রোফাইল",
    navEarn: "আয় করুন",
    addFunds: "টাকা যোগ করুন",
    selectPayment: "পেমেন্ট পদ্ধতি নির্বাচন করুন",
    amount: "পরিমাণ",
    profileSettings: "LANGUAGE",
    language: "ভাষা",
    theme: "থিম",
    light: "লাইট",
    dark: "ডার্ক",
    logout: "লগআউট",
    customerCare: "কাস্টমার কেয়ার",
    watchAds: "বিজ্ঞাপন দেখুন ও আয় করুন",
    watchAnAd: "বিজ্ঞাপন দেখুন",
    adsWatched: "আজকের দেখা বিজ্ঞাপন",
    youEarned: "আপনি আয় করেছেন",
    adLimitReached: "আপনি দৈনিক বিজ্ঞাপন দেখার সীমা অতিক্রম করেছেন।",
    watchAdsScreenTitle: "বিজ্ঞাপন দেখুন ও আয় করুন",
    watchAdsScreenDescription: "পুরস্কার অর্জন করতে এবং আপনার ব্যালেন্স টপ আপ করতে ছোট ভিডিও বিজ্ঞাপন দেখুন।",
    rewardPerAd: "প্রতি বিজ্ঞাপনে পুরস্কার",
    dailyAdLimit: "দৈনিক বিজ্ঞাপনের সীমা",
    totalEarned: "মোট উপার্জন",
    totalAdsWatched: "মোট দেখা বিজ্ঞাপন",
    ads: "বিজ্ঞাপন",
    uid: "প্লেয়ার ইউআইডি",
    searchDiamonds: "ডায়মন্ড সার্চ করুন (যেমন, ১০০)",
    noOffersFound: "কোনো অফার পাওয়া যায়নি।",
    purchaseHistory: "ক্রয়ের ইতিহাস",
    statusCompleted: "সম্পন্ন",
    statusPending: "পেন্ডিং",
    statusFailed: "ব্যর্থ",
    hi: "হাই",
    availableBalance: "বর্তমান ব্যালেন্স",
    supportPin: "সাপোর্ট পিন",
    weeklySpent: "সাপ্তাহিক খরচ",
    totalSpent: "মোট খরচ",
    totalDeposit: "মোট জমা",
    totalOrder: "মোট অর্ডার",
    logoutConfirmTitle: "লগআউট নিশ্চিত করুন",
    logoutConfirmMessage: "আপনি কি নিশ্চিতভাবে লগআউট করতে চান?",
    logoutConfirmButton: "নিশ্চিত করুন",
    viewDetails: "বিস্তারিত দেখুন",
    contactSupport: "সাপোর্টে যোগাযোগ করুন",
    myOrders: "আমার অর্ডার",
    myCodes: "আমার কোড",
    myTransaction: "আমার লেনদেন",
    contactUs: "যোগাযোগ করুন",
    getInTouch: "যোগাযোগ করুন",
    support: "সাপোর্ট",
    fundsAddedSuccessfully: "সফলভাবে টাকা যোগ করা হয়েছে!",
    addFundsError: "অনুগ্রহ করে টাকার পরিমাণ লিখুন এবং একটি অর্থপ্রদানের পদ্ধতি নির্বাচন করুন।",
    changePassword: "পাসওয়ার্ড পরিবর্তন",
    changePasswordTitle: "পাসওয়ার্ড পরিবর্তন করুন",
    currentPassword: "বর্তমান পাসওয়ার্ড",
    newPassword: "নতুন পাসওয়ার্ড",
    confirmNewPassword: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
    updatePassword: "পাসওয়ার্ড আপডেট করুন",
    passwordChangedSuccess: "পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে!",
    passwordsDoNotMatch: "পাসওয়ার্ড দুটি মিলছে না।",
    incorrectCurrentPassword: "বর্তমান পাসওয়ার্ডটি ভুল।",
    delete: "মুছে ফেলুন",
    deleteConfirmTitle: "মুছে ফেলা নিশ্চিত করুন",
    deleteConfirmMessage: "আপনি কি নিশ্চিতভাবে এই অর্ডারটি মুছে ফেলতে চান? এই কাজটি আর ফেরানো যাবে না。",
    deleteConfirmButton: "মুছে ফেলুন",
    ordersEmpty: "আপনার ক্রয়ের ইতিহাস খালি。",
    rewardAdded: "আপনার ব্যালেন্সে যোগ করা হয়েছে!",
    minDepositError: `সর্বনিম্ন জমার পরিমাণ ৳${MIN_DEPOSIT_AMOUNT}।`,
    nextStep: "পরবর্তী",
    previousStep: "পূর্ববর্তী",
    paymentInstructionsTitle: "পেমেন্ট নির্দেশনা",
    paymentInstructionsBody: "অনুগ্রহ করে নিচের {methodName} নম্বরে ঠিক {currency}{amount} পাঠান। তারপর পরবর্তী ধাপে ট্রানজেকশন আইডি লিখুন।",
    accountNumberLabel: "নম্বর",
    copy: "কপি",
    copied: "কপি হয়েছে!",
    paymentSentConfirmation: "আমি টাকা পাঠিয়েছি",
    transactionIdLabel: "ট্রানজেকশন আইডি",
    transactionIdPlaceholder: "এখানে TrxID লিখুন",
    submitTransaction: "জমা দিন",
    paymentPendingTitle: "অনুরোধ জমা হয়েছে",
    paymentPendingMessage: "আপনার টাকাটি ১০ মিনিটের মধ্যে আপনার একাউন্টে এড হয়ে যাবে, যদি পেমেন্ট সফলভাবে পৌঁছায়।",
    addMoreMoney: "আরও টাকা যোগ করুন",
    transactionIdRequired: "ট্রানজেকশন আইডি আবশ্যক。",
    nextAdIn: "পরবর্তী বিজ্ঞাপন",
    insufficientBalance: "অপর্যাপ্ত ব্যালেন্স।",
    newBalance: "নতুন ব্যালেন্স",
    editProfileTitle: "প্রোফাইল সম্পাদনা করুন",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    changePhoto: "ছবি পরিবর্তন করুন",
    saving: "সংরক্ষণ করা হচ্ছে...",
    changesSaved: "পরিবর্তন সংরক্ষিত!",
    uidOptional: "ইউআইডি (ঐচ্ছিক)",
    howToBuyDiamond: "ডায়মন্ড কীভাবে কিনবেন (টিউটোরিয়াল ভিডিও)",
    contactCallUs: "ফোন করুন",
    contactWhatsApp: "হোয়াটসঅ্যাপ",
    contactTelegram: "টেলিগ্রাম",
    contactEmailUs: "ইমেল করুন",
    rewardDepositMessage: "ওয়ালেটে +{amount}!",
    levelUpPackages: "লেভেল আপ",
    memberships: "মেম্বারশিপ",
    premiumApps: "প্রিমিয়াম অ্যাপস",
    notifications: "নোটিফিকেশন",
    noNotifications: "কোনো নোটিফিকেশন নেই।",
    markAllRead: "সব পড়া হয়েছে হিসেবে মার্ক করুন",
    'Level 6 Package': 'লেভেল ৬ প্যাকেজ',
    'Level 10 Package': 'লেভেল ১০ প্যাকেজ',
    'Level 15 Package': 'লেভেল ১৫ প্যাকেজ',
    'Level 20 Package': 'লেভেল ২০ প্যাকেজ',
    'Level 25 Package': 'লেভেল ২৫ প্যাকেজ',
    'Level 30 Package': 'লেভেল ৩০ প্যাকেজ',
    'Weekly Membership': 'সাপ্তাহিক মেম্বারশিপ',
    'Monthly Membership': 'মাসিক মেম্বারশিপ',
  }
};